client_config_backend: settings
client_config:
  client_email: smartlidarmolas@temperaturesensor-311610.iam.gserviceaccount.com
  client_id: "116467094644075890084"
  client_secret: gNIDrrzQJpokj9nxwRmgKSse

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install